spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true
    database: h2
  shell:
    history:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2
      settings.trace: false
      settings.web-allow-others: false
  liquibase:
    enabled: true
    drop-first: true
logging:
  level:
    root: info