server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  r2dbc:
    url: r2dbc:h2:mem:///maindb
    username: sa
    password:
    pool:
      enabled: true
    properties:
      MULTI_THREADED: TRUE
      DB_CLOSE_ON_EXIT: FALSE
r2dbc:
  migrate:
    resources:
      - resourcesPaths:
          - classpath:/db/migration/*.sql
logging:
  level:
    root: info
    org.springframework.web: warn