server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
    pool:
      enabled: true
  liquibase:
    enabled: true
    drop-first: true
logging:
  level:
    root: info
    org.springframework.web: warn
    liquibase: warn