spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    database: h2
  data:
    mongodb:
      host: localhost
      port: 27017
      database: receipts_db
  shell:
    history:
      enabled: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2
      settings.trace: false
      settings.web-allow-others: false
  liquibase:
    enabled: true
    drop-first: true
logging:
  level:
    root: info
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local