version: '3.9'

services:
  h2:
    image: oscarfonts/h2
    container_name: h2_server
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists -web -webAllowOthers -webPort 8082
    ports:
      - "8082:8082"  # Web-консоль H2
      - "1521:1521"  # Порт для JDBC подключения
    networks:
      - hw17-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hw17
    depends_on:
      h2:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521//opt/h2-data/maindb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_LIQUIBASE_ENABLED: true
    ports:
      - "8080:8080"
    networks:
      - hw17-network
    restart: unless-stopped

volumes:
  h2-data:

networks:
  hw17-network:
    driver: bridge